### PR TITLE
Village Mechanic for Custom Entity Tutorial

### PR DESCRIPTION
**Pull request by AeroForta**
New article for creating village mechanic for custom entity

Also please check the grammar as English is not my first language

### CODE REVIEW

**Comment by SirLich** [comment]
Hi! There are a lot of formatting issues here. I will probably merge this in tonight, and then fix the issues in a second PR. 

If you want to try and fix them yourself:

---

:::Warning
My warning Message
::::

Instead of **Warning**

---

Make sure every code-block is wrapped in json code-blocks. Consider adding CodeHeaders.

**Comment by AeroForta** [comment]
I actually try to use 
:::Warning
My warning Message
::::
But in preview it doesn't seem to do anything

**Comment by MedicalJewel105** [comment]
Im going to work on it ☠

**Comment by 7dev7urandom** [comment]
> I actually try to use
> :::Warning
> My warning Message
> ::::
> But in preview it doesn't seem to do anything

That's normal. That syntax is used in the page when it is built, but it won't show in most markdown renderers.

**Pull request closed without merging**
